print("2.1 ")
a1 = str(input("первая строка: "))
a2 = str(input("Вторая строка: "))
print(a1+""+a2)
print("2.2 ")
a1 = str(input("первая строка: "))
a2 = str(input("Вторая строка: "))
print(2*(a1 + " "),3*(a2 + " "))
print("2.3 ")
a1 = str(input("первое число: "))
a2 = str(input("Второе число: "))
print("Переменная а = "+a1+" Переменная b = "+a2)
print("2.4 ")
a1 = str(input("Введите строку: "))
print("Строка:",a1+".","Длина:",len(a1))
print("2.5 ")
a1 = str(input("первое слово: "))
a2 = str(input("второе слово: "))
print(a1 in a2, a1 == a2, a1 > a2, a1 < a2)
print("2.6 ")
a1 = str(input("первая буква: "))
a2 = str(input("вторая буква: "))
print("Коды: a =",ord(a1),"z =", ord(a2))
print("2.7 ")
a1 = str(input("введите строку: "))
print(a1[0]+a1[-1])
print("2.8 ")
a1 = str(input("введите слово: "))
print(a1[0:4])
print("2.9 ")
a1 = str(input("введите строку: "))
print(a1[-4:-1]+a1[-1])
print("2.10 ")
a1 = str(input("введите строку: "))
print(a1[1::2])
print("2.11 ")
a1 = str(input("введите строку 1: "))
a2 = str(input("введите строку 2: "))
print(a1[0::2],a2[1::2])
print("2.12 ")
a1 = str(input("введите слово: "))
print(reversed(a1[0:5]))
print("2.13 ")
a1 = str(input("введите строку 1: "))
a2 = str(input("введите строку 2 длиннее первой: "))
print(a2[0:len(a1)+1])
print("2.14 ")
a1 = str(input("введите строку 1: "))
a2 = str(input("введите строку 2 короче первой: "))
print(a1[1:len(a2)+1:2] == a2[1::2])
print("2.15 ")
a1 = str(input("введите слово: "))
print(a1.capitalize)
print("2.16 ")
a1 = str(input("введите строку: "))
print(a1.count("-"))
print("2.17 ")
a1 = str(input("введите строку: "))
print(a1.find("ra"))
print("2.18 ")
a1 = str(input("введите строку: "))
a1 = a1.replace('---','-')
a1 = a1.replace('--','-')
print(a1)
print("2.19")
a1 = str(input("введите 1 строку: "))
a2 = str(input("введите 2 строку: "))
a3 = str(input("введите 3 строку: "))
print(a1.rjust(3,"0")+"\n"+a2.rjust(3,"0")+"\n"+a3.rjust(3,"0"))
print("2.20")
a1 = str(input("введите строку: "))

print(a1.count(" ")+1)
print("2.21")
a1 = str(input("введите строку: "))
a1 = a1.replace(" ",";")
print(a1)
print("2.22")
print("Тема занятия \"спецсимволы\"")
print("2.23")
a1 = str(input("Введите 2 слова в 1 строку: "))
a1 = a1.replace(" ","\\")
print(a1)
print("2.24")
a1 = str(input("Введите 2 слова в 1 строку: "))
a1 = a1.replace(" ","\'",1)
a1 = a1.replace(" ","\"")
print(a1)
print("2.25")
a1 = r"C:\Windows\netdisc\drivers\tc\hosts"
print(a1)
print("2.26")
