print("3.1")
a1 = input("\nВведите 3 числа через пробел:\n")
a1 = a1.split()
print(f"[{a1[0]}, {a1[1]}, {a1[2]}]")
print("\n3.2")
a1 = (input("\nВведите названия 4 городов\n"))
a1 = a1.split()
a2 = input("\nВведите искомый город:\n")
print(a2 in a1)
print("\n3.3")
a1 = (input("\nВведите названия городов\n"))
a1 = a1.split()
print(a1[-1])
print("\n3.4")
a1 = (input("\nВведите оценки\n"))
a1 = a1.split