print("4.1")
t = (5.45, -18.9)
lst = list(map(int, input().split()))
t += tuple(lst)
print("4.2")
cities = tuple(input().split())
result = cities + ("Москва",) * ("Москва" not in cities)
print(" ".join(result))
print("4.3")
cities = tuple(input().split())
result = cities[:-2] + (cities[-1],)
print(" ".join(result))
print("4.4")
students = tuple(input().split())
search_name = input()
count = students.count(search_name)
print(count)
print("4.5")
grades = tuple(map(int, input().split()))
average = round(sum(grades) / len(grades), 1)
print(average)
print("4.6")
cities = tuple(input().split())
start_city = input()
start_index = cities.index(start_city)
result = cities[start_index::2]
print(" ".join(result))
print("4.7")
grades = tuple(map(int, input().split()))
result = grades[2:7][::-1]
print(" ".join(map(str, result)))
print("4.8")
t1 = tuple(map(int, input().split()))
t2 = tuple(map(int, input().split()))
t3 = tuple(map(int, input().split()))
nested_tuple = (t1, t2, t3)
sum_last_elements = sum(t[-1] for t in nested_tuple)
print(sum_last_elements)
print("4.9")
length, width, height = map(float, input().split())
volume = length * width * height
formatted_volume = f"{volume:.2f}".replace('.', '_').replace('_', '.', 1).replace('.', '_', -3)
print(formatted_volume)
print("4.10")
t1 = tuple(map(int, input().split()))
t2 = tuple(map(int, input().split()))
t3 = tuple(map(int, input().split()))
nested_tuple = (t1, t2, t3)
averages = [round(sum(t) / len(t), 1) for t in nested_tuple]
print(" ".join(map(str, averages)))